name: AllBarkNoBytes
main: io.github.cccm5.AllBarkNoBytes.BarkMain
version: 0.0.2
commands:
   bark:
     description: Gets the bark wand
     aliases: [wood, log]
     permission: AllBarkNoBytes.wand
permissions:
   AllBarkNoBytes.wand:
        description: Allows a user to use and get the wand
        default: op